package com.sample

global com.sample.GUI gui

declare GUIState
	question : String @key
	possibleAnswers : String[] @key
	chosenAnswer : String @key
end

declare GUIResult
	result : String @key
end

function String askQuestion(GUI gui, String question, String[] possibleAnswers) {
    String answer = gui.askQuestion(question, possibleAnswers);
    return answer;
}

function void showResult(GUI gui, GUIResult result) {
    gui.showResult(result.getResult());
}

function String getQuestionById(int id) {
	switch(id) {
		case 1: return "How old are you?";
		case 2: return "Are you really doing this quiz? Impressive! Do your parents want you to be a child prodigy?";
        case 3: return "Are you prepared to put in a lot of practice time?";
        case 4: return "Do you want to drive your family mad?";
        case 5: return "Do you have a big house?";
        case 6: return "Do you want to play in an orchestra?";
        case 7: return "Do you hate your neighbours?";
        case 8: return "Dast thou wish to sit or stand?";
        case 9: return "Do you have a good sense of rhythm & timing?";
        case 10: return "Do you like folk music?";
        case 11: return "Do you have unlimited time, lots of money and a van?";
        case 12: return "Do you consider yourself to have some musical ability?";
        case 13: return "Do you have nerves and an upper lip of steel?";
        case 14: return "Fancy yourself as a composer?";
        case 15: return "Are you more Mozart or more McCartney?";
        case 16: return "Do you want to be centre of attention?";
        case 17: return "Do you enjoy lifting heavy weights?";
		default: return "Invalid";
	}
}

rule "Init"
    when
    then
    	String question = getQuestionById(1);
		String[] possibleAnswers = {"0-5", "6-12", "13+"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
		insert(state);
end

rule "How old are you#13+"
	when 
		GUIState(question == getQuestionById(1) && chosenAnswer == "13+")
	then
		String question = getQuestionById(11);
		String[] possibleAnswers = {"Not really", "Yes I've also got a chauffeur"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
		insert(state);
end

rule "unlimited time and money#Yes"
	when 
		GUIState(question == getQuestionById(11) && chosenAnswer == "Yes I've also got a chauffeur")
	then
        GUIResult result = new GUIResult("Harp");
        showResult(gui, result);	
        insert(result);
end

rule "unlimited time and money#not really"
	when 
		GUIState(question == getQuestionById(11) && chosenAnswer == "Not really")
	then
		String question = getQuestionById(12);
		String[] possibleAnswers = {"Yes, I'm amazing", "I have some", "Not an iota"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
		insert(state);
end

rule "musical ability#not iota"
	when 
		GUIState(question == getQuestionById(12) && chosenAnswer == "Not an iota")
	then
        GUIResult result = new GUIResult("Comb and tissue paper");
        showResult(gui, result);	
        insert(result);
end

rule "musical ability#im amazing"
	when 
		GUIState(question == getQuestionById(12) && chosenAnswer == "Yes, I'm amazing")
	then
		String question = getQuestionById(13);
		String[] possibleAnswers = {"Not quite", "That sounds just like me"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
		insert(state);
end

rule "piano"
	when 
		GUIState(question == getQuestionById(13) && chosenAnswer == "Not quite") 
		|| GUIState(question == getQuestionById(3) && chosenAnswer == "Yes")
		|| GUIState(question == getQuestionById(15) && chosenAnswer == "Mozart")
		|| GUIState(question == getQuestionById(16) && chosenAnswer == "Yes I'm gonna be a star")
		|| GUIState(question == getQuestionById(6) && chosenAnswer == "Too many people too much noise")
		
	then
        GUIResult result = new GUIResult("Piano");
        showResult(gui, result);	
        insert(result);
end

rule "nerves#that sounds like me"
	when 
		GUIState(question == getQuestionById(13) && chosenAnswer == "That sounds just like me")
	then
        GUIResult result = new GUIResult("French horn");
        showResult(gui, result);	
        insert(result);
end

rule "How old are you#0-5"
	when 
		GUIState(question == getQuestionById(1) && chosenAnswer == "0-5")
	then
		String question = getQuestionById(2);
		String[] possibleAnswers = {"Yes!", "No, I'm happy just to play"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
		insert(state);
end
	
rule "Are you really doing this quiz#Yes"
	when 
		GUIState(question == getQuestionById(2) && chosenAnswer == "Yes!")
	then
        GUIResult result = new GUIResult("Violin");
        showResult(gui, result);	
        insert(result);
end

rule "Are you really doing this quiz#No How old are you#6-12"
	when 
		GUIState((question == getQuestionById(2) && chosenAnswer == "No, I'm happy just to play") || (question == getQuestionById(1) && chosenAnswer == "6-12"))
	then
		String question = getQuestionById(3);
		String[] possibleAnswers = {"No I just want to get playing as quickly as possible", "Yes"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
		insert(state);
end

rule "Are you prepared to put in a lot of practice time#no"
	when 
		GUIState(question == getQuestionById(3) && chosenAnswer == "No I just want to get playing as quickly as possible")
	then
		String question = getQuestionById(4);
		String[] possibleAnswers = {"Wouldn't I just", "I'm not a brat!"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
		insert(state);
end

rule "Do you want to drive your family mad#wouldnt"
	when 
		GUIState(question == getQuestionById(4) && chosenAnswer == "Wouldn't I just")
	then
        GUIResult result = new GUIResult("Recorder");
        showResult(gui, result);	
        insert(result);
end

rule "Big house"
	when 
		GUIState(question == getQuestionById(4) && chosenAnswer == "I'm not a brat!")
		|| GUIState(question == getQuestionById(16) && chosenAnswer == "Not really I'm a team player")
	then
        String question = getQuestionById(5);
        String[] possibleAnswers = {"I live in a church", "There's plenty of room", "It's more compact and bijou"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end

rule "House#Church"
	when 
		GUIState(question == getQuestionById(5) && chosenAnswer == "I live in a church")
	then
        GUIResult result = new GUIResult("Organ");
        showResult(gui, result);	
        insert(result);
end

rule "House#Plenty"
	when 
		GUIState(question == getQuestionById(5) && chosenAnswer == "There's plenty of room")
    then
        String question = getQuestionById(6);
        String[] possibleAnswers = {"Only if it's baroque", "My life is like a symphony", "Too many people too much noise"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end

rule "House#compact"
	when 
		GUIState(question == getQuestionById(5) && chosenAnswer == "It's more compact and bijou")
    then
        String question = getQuestionById(7);
        String[] possibleAnswers = {"With a passion", "No, they're quite nice"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end

rule "orchestra#baroque"
	when 
		GUIState(question == getQuestionById(6) && chosenAnswer == "Only if it's baroque")
    then
        String question = getQuestionById(8);
        String[] possibleAnswers = {"Sitteth", "Standeth"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end

rule "sit or stand#sitteth"
	when 
		GUIState(question == getQuestionById(8) && chosenAnswer == "Sitteth")
	then
        GUIResult result = new GUIResult("Lute");
        showResult(gui, result);	
        insert(result);
end

rule "sit or stand#Standeth"
	when 
		GUIState(question == getQuestionById(8) && chosenAnswer == "Standeth")
	then
        GUIResult result = new GUIResult("Harpsichord");
        showResult(gui, result);	
        insert(result);
end

rule "neighbours hate#with a passion"
	when 
		GUIState(question == getQuestionById(7) && chosenAnswer == "With a passion")
    then
        String question = getQuestionById(9);
        String[] possibleAnswers = {"I'm a human metronome", "It's OK I guess"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end

rule "sense of rhythm#metronome"
	when 
		GUIState(question == getQuestionById(9) && chosenAnswer == "I'm a human metronome")
	then
        GUIResult result = new GUIResult("Percussion");
        showResult(gui, result);	
        insert(result);
end

rule "sense of rhythm#OK"
	when 
		GUIState(question == getQuestionById(9) && chosenAnswer == "It's OK I guess")
	then
        GUIResult result = new GUIResult("Trombone");
        showResult(gui, result);	
        insert(result);
end

rule "neighbours hate#no"
	when 
		GUIState(question == getQuestionById(7) && chosenAnswer == "No, they're quite nice")
    then
        String question = getQuestionById(10);
        String[] possibleAnswers = {"I'm not a hippy", "I always wear flowers in my hair"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end

rule "folk music#im not hippy"
	when 
		GUIState(question == getQuestionById(9) && chosenAnswer == "I'm not a hippy")
	then
        GUIResult result = new GUIResult("Digital piano");
        showResult(gui, result);	
        insert(result);
end

rule "acoustic guitar"
	when 
		GUIState(question == getQuestionById(9) && chosenAnswer == "I always wear flowers in my hair") ||
		 GUIState(question == getQuestionById(15) && chosenAnswer == "McCartney")
	then
        GUIResult result = new GUIResult("Acoustic guitar");
        showResult(gui, result);	
        insert(result);
end

rule "ability#some"
	when
		GUIState(question == getQuestionById(12) && chosenAnswer == "I have some")
	then
		String question = getQuestionById(14);
        String[] possibleAnswers = {"Yes roll over Beethoven", "Not particulary"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end

rule "composer#yes"
	when
		GUIState(question == getQuestionById(14) && chosenAnswer == "Yes roll over Beethoven")
	then
		String question = getQuestionById(15);
        String[] possibleAnswers = {"Mozart", "McCartney"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end

rule "composer#no"
	when
		GUIState(question == getQuestionById(14) && chosenAnswer == "Not particulary")
	then
		String question = getQuestionById(16);
        String[] possibleAnswers = {"Yes I'm gonna be a star", "Not really I'm a team player"};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end

rule "orchestra#symphony"
	when
		GUIState(question == getQuestionById(6) && chosenAnswer == "My life is like a symphony")
	then
		String question = getQuestionById(17);
        String[] possibleAnswers = {"I'm often mistaken for Superman", "I'm not a wimp but..."};
        String answer = askQuestion(gui, question, possibleAnswers);
        GUIState state = new GUIState(question, possibleAnswers, answer);
        insert(state);
end